exclude: "\
^infra/foo.tf|\
^infra/ec2.tf|\
^infra/bar.tf"

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # frozen: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

# - repo: https://github.com/antonbabenko/pre-commit-terraform
#   rev: d9addbeb3614a69d4f96a60d3a090bfddfbb1596  # frozen: v1.88.4
#   hooks:
#   - id: terraform_fmt

- repo: local
  hooks:
  - id: terraform_fmt
    name: Terraform fmt
    description: Rewrites all Terraform configuration files to a canonical format.
    entry: terraform fmt
    language: system
    files: (\.tf|\.tfvars)$
    exclude: \.terraform/.*$
